### ISSUE TITLE
restartPolicy is not copied to remote pod

### ISSUE THREAD

**Issue by jalola** [liqotech/liqo#1033]
#### What happened:
I have a pod deployed with `restartPolicy: Never`, the local pod has correct `restartPolicy` which is `Never`.
The remote pod does not, it has `restartPolicy: Always`
#### What you expected to happen:
The remote pod should have `restartPolicy: Never`

#### How to reproduce it (as minimally and precisely as possible):

Deploy a pod with `restartPolicy: Never` on local cluster that will be offloaded to remote cluster.
Check the `restartPolicy` of the pod on remote cluster

```
apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    role: myrole
  namespace: my-namespace
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
  restartPolicy: Never
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: liqo.io/type
            operator: In
            values:
            - virtual-node
          - key: liqo.io/type
            operator: In
            values:
            - virtual-node
        - matchExpressions:
          - key: liqo.io/type
            operator: In
            values:
            - virtual-node
          - key: liqo.io/type
            operator: NotIn
            values:
            - virtual-node
```

#### Environment:
- Liqo version: v0.3.2-beta.2
- Kubernetes version (use `kubectl version`): v1.21.0
- Cloud provider or hardware configuration: 2 EKS clusters
- Network plugin and version:
- Install tools:
- Others:
