### ISSUE TITLE
Question: DNS between nodes

### ISSUE THREAD

**Issue by jensg-st** [liqotech/liqo#1109]
Hi,

this is not a bug report but a question. I'm just wondering how the DNS works between nodes. My setup consists of two k3s clusters with one node each. Both have the same service and pod CIDRs. To test connectivity I created 3 namespaces ns1, ns2 and ns3. 

Namespace ns1 has a simple grpc and http server running:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: ns1
spec:
  selector:
    matchLabels:
      run: server
  template:
    metadata:
      labels:
        run: server
    spec:
      containers:
      - name: server
        image: gerke74/server
        ports:
        - containerPort: 7777
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: ns1
  labels:
    run: server
spec:
  ports:
  - port: 7777
    name: grpc
    protocol: TCP
  - port: 8090
    name: http
    protocol: TCP
  selector:
    run: server
```

Namespace ns2 is a test namespace where I'm running a simple client for those two servers (GRPC & HTTP).  That works of course. The third namespace ns3 is labeled for liqo. If I run the client in that namespace it starts up correctly on the remote node but can not resolve the server name *server.ns1*. 

For me the main question is how DNS resolution works in liqo. Does it only work with pods running in the liqo enabled namespace or is it supposed to work across other namespaces in the cluster or is there something wrong with that setup?

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: ns3
spec:
  selector:
    matchLabels:
      run: client
  template:
    metadata:
      labels:
        run: client
    spec:
      containers:
      - name: client
        image: gerke74/client
        command: ["/client"]
        args: ["server.ns1:7777", "http://server.ns1:8090"]
```
