### ISSUE TITLE
Some pod fields are being stripped

### ISSUE THREAD

**Issue by jonathon2nd** [liqotech/liqo#1152]
#### What happened:

`envFrom`, `lifecycle`, and a cephfs volume mount are all being stripped away when the pod goes to run on the foreign cluster. Funny enough the secrets being referred to by `envFrom` are replicated

#### What you expected to happen:
I expect those items to not be stripped out of the pod yaml

#### How to reproduce it (as minimally and precisely as possible):
Deploy this yaml. For this example the `infra` namespace has been offloaded.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  annotations:
    {}
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-infra-test
  namespace: infra
spec:
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-infra-test
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-infra-test
    spec:
      containers:
        - imagePullPolicy: Always
          name: container-0
          __active: true
          image: phusion/baseimage:focal-1.0.0
          lifecycle:
            preStop:
              exec:
                command:
                  - sleep
                  - '5'
          stdin: false
          stdinOnce: false
          tty: false
          envFrom:
            - prefix: ''
              secretRef:
                name: infra-dev-mongodb
                optional: false
      restartPolicy: Always
  replicas: 4
```
You will see that the envFrom and lifecycle are missing on the remote pod, when viewed on the remote cluster. When viewing the remote pod from the main cluster, it appears that the values are there, but they are not.

#### Environment:
- Liqo version: v0.3.2
- Kubernetes version (use `kubectl version`): 
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"b631974d68ac5045e076c86a5c66fba6f128dc72", GitTreeState:"clean", BuildDate:"2022-01-19T17:45:53Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: on-prem with terraform created nodes, and OVH remote managed k8s clsuter
- Network plugin and version: calico and canal
- Install tools: helm
- Others:
