### ISSUE TITLE
no connectivity for service CIDR 

### ISSUE THREAD

**Issue by jcputter** [liqotech/liqo#1385]
#### What happened:

We deployed Liqo to two of our clusters, i can confirm pod-to-pod connectivity however i'm not able to reach svc endpoints from either side
```
networkManager:
    config:
        additionalPools: []
        podCIDR: ${pod_network}
        reservedSubnets: []
        serviceCIDR: ${service_network}
    imageName: liqo/liqonet
    pod:
        annotations: {}
        extraArgs: []
        labels: {}
```
Our Pod and Service CIDR's are not overlapping, what i can see is that from side A if we try do a traceroute to a svc endpoint in Side B the routing path does not go via Liqo 

#### What you expected to happen:

I expected pod-to-pod and pod-to-service connectivity 

#### Environment:
- Liqo version: v0.5.4
- Kubernetes version (use `kubectl version`): 1.23
- Cloud provider or hardware configuration: EKS
- Network plugin and version: VPC-CNI
- Install tools: helm/terraform
- Others:
