### ISSUE TITLE
Install Liqo on Digital Ocean

### ISSUE THREAD

**Issue by cheina97** [liqotech/liqo#1668]
#### What happened:

The installation of liqo on a Digital Ocean's cluster with liqoctl fails. The problem is related to the liqo-gateway's service and digital ocean's load balancer health check.  The digital ocean's load balancer does not support an health check based on UDP.

#### What you expected to happen:

The assigned load balancer should use a TCP service in order to keep it alive.

#### How to reproduce it (as minimally and precisely as possible):

```bash
doctl kubernetes cluster kubeconfig show doks-1 > "$HOME/liqo_kubeconf_do1.yaml"
liqo1podcidr=$(doctl kubernetes cluster get doks-1 --verbose -o json|jq ".[0].cluster_subnet" | cut -d "\"" -f 2)
liqo1servicecidr=$(doctl kubernetes cluster get doks-1 --verbose -o json|jq ".[0].service_subnet" | cut -d "\"" -f 2)
export KUBECONFIG="$HOME/liqo_kubeconf_do1.yaml"
liqoctl install --pod-cidr "$liqo1podcidr" --service-cidr "$liqo1servicecidr" --cluster-name doks-1
```

#### Environment:
- Liqo version: v0.7.0
- Kubernetes version (use `kubectl version`): v1.25.0
- Cloud provider or hardware configuration: Digital Ocean
- Install tools: liqoctl

## Workaround:

The solution is to put a sidecar container (a simple nginx) inside the liqo-gateway pod and modify the liqo-gateway's service in order to make the nginx server reachable through the LoadBalancer.

``` bash
export KUBECONFIG="$HOME/liqo_kubeconf_do1.yaml"
kubectl wait --for=condition=ready pod  -l app.kubernetes.io/instance=liqo-gateway -n liqo
kubectl patch -n liqo services liqo-gateway --patch-file liqo-gateway-svc-patch.yaml
kubectl patch -n liqo deployments.apps liqo-gateway --patch-file liqo-gateway-deploy-patch.yaml
```
\
That's inside file `liqo-gateway-deploy-patch.yaml`:

``` yaml
spec:
  template:
    spec:
      containers:
      - name: lb-replier
        image: nginx
        ports:
          - containerPort: 80
            name: lb-replier
            protocol: TCP
```
\
That's inside file `liqo-gateway-svc-patch.yaml`:
``` yaml
metadata:  
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-port: "80"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: "http"
spec:
  ports:
  - name: lb-replier
    port: 80
    protocol: TCP
    targetPort: 80
```
