### ISSUE TITLE
[Feature] Add a Declarative Way to Handle Virtual Nodes Lifecycle

### ISSUE THREAD

**Issue by aleoli** [liqotech/liqo#1766]
### Describe the solution you'd like

The possibility of having a declarative way to handle the lifecycle of a liqo virtual node.

We need a new CRD and a new operator reconciling it to do that.
This new resource should be similar to this one:

```yaml
apiVersion: virtualkubelet.liqo.io/v1alpha1
kind: VirtualNode
metadata:
  name: liqo-node-name
  namespace: tenant-namespace
spec:
  clusterIdentity:
    clusterID: ...
    clusterName: ...
  template: # -> the template for the VK deployment, it can be helpful to override specific values on it
  offloadingPatch:
    nodeSelector: # -> the node selector that will be added to each pod offloaded by this virtual node
    tolerations: [] # -> the tolerations that will be added to each pod offloaded by this virtual node
    affinities: [] # -> the affinities that will be added to each pod offloaded by this virtual node
  createNode: true # -> whether to create or not the virtual node, it can be possible to enable service-only reflection without nodes
  kubeconfigSecretRef:
    name: kubeconfig-secret
  images: []
  resourceQuota:
    memory: 3Gi
    cpu: 3
    ...
  labels:
    ...
  storageClasses: []
status:
  conditions:
  - type: VirtualKubelet
    status: Running
    reason: ...
    transitionTimestamp: ...
  - type: Node
    status: Running
    reason: ...
    transitionTimestamp: ...
```

### Required Steps

- [x] definition of the new CRD
- [x] creation of a new operator creating virtual kubelet deployments starting from this resource
- [x] the virtual node controller (already existing operator) should reconcile this new resource instead of nodes
  - [x] only a single `NamespaceMap` should exist for each cluster, not for each virtual node
- [x] check that the cluster selectors are still working also in the case multiple virtual nodes are targeting the same cluster id
