### ISSUE TITLE
[Feature] Make it possible to target a Cluster with Multiple Virtual Nodes

### ISSUE THREAD

**Issue by aleoli** [liqotech/liqo#1768]
### Describe the solution you'd like

It should be possible to have multiple virtual nodes targeting the same remote cluster.
It could be helpful for many reasons, for instance:

1. make the other cluster aware of each remote node to have better scheduling and affinities enforcement
2. share huge resource pools with another cluster while keeping the virtual node size quite small, avoiding a "black hole" effect during scheduling

The current `ResourceOffer` CRD spec should have two new fields (mutually exclusive to each other) to enable the remote cluster to handle node names.

```yaml
apiVersion: offloading.liqo.io/v1alpha1
kind: ResourceOffer
metadata:
  namespace: tenant-namespace
spec:
  nodeName: ... # -> the exact node name to be used in the remote cluster, it can be used in case of exact replication of local nodes
  nodeNamePrefix: ... # -> a prefix used by the remote cluster to generate node names; it can be used in case of resource pools
```

The creation of multiple resource offers will trigger the creation of multiple `VritualNode` resources and then multiple additional nodes.

![new_workflow drawio](https://user-images.githubusercontent.com/36957454/230344472-107d45ba-7fb0-444f-b860-a3743c3cd71f.png)

### Required Steps

- [x] add fields to the CRD
- [x] add a new configuration to the `ResourceRequest` operator to enable the creation of a `ResourceOffer` for each node
- [x] modify the resource offer operator to create the new `VirtualNode` (see #1766) CRD instead of VK Deployments
- [x] check and fix the [plugin interface](https://github.com/liqotech/liqo-resource-plugins) 

### Future Steps

- the resource offer operator may choose to split a single offer to multiple VirtualNodes to avoid the "black hole" effect
