### ISSUE TITLE
[Feature] IPAM API

### ISSUE THREAD

**Issue by cheina97** [liqotech/liqo#1990]
# IPAM API

## What is IPAM

**IPAM**, which stands for **IP Address Management**, is a crucial component in network administration. It refers to the planning, tracking, and management of IP addresses within a network infrastructure.
IPAM is a component already present in Liqo. It is managed by **liqo-network-manager** and is possible to interact with it through a gRPC server. In Liqo the IPAM is responsible for the remapping of IPs, in particular, it manages the remapping of PodCIDR and ExternalCIDR when one of them conflicts with an already-used CIDR.

## What's new

The Liqo team plans to introduce a declarative approach to interact with IPAM. New CRDs will be introduced inside the Liqo `ipam.liqo.io/v1alpha1` group:
- `networks.ipam.liqo.io`: remaps entire network CIDRs:
  - the status shows how a network CIDR of a remote cluster (specified in a specific label) has been remapped in the local cluster 
  - each Network resource refers to one single remote cluster
- `ips.ipam.liqo.io`:  remaps single IPs:
  - the status shows how each remote cluster has remapped the IP
  - the IP can be external to the local cluster
  - it is also possible to specify a _Service template_ to create an associated Service to expose the specified IP. If the resource is deployed on an offloaded namespace, the service (and its endpointslices) will be reflected on the remote clusters (with the remapped IP if necessary).

#### Old
![ipamissueOld](https://github.com/liqotech/liqo/assets/33266330/0a4c2bf7-d79a-468e-80f6-d739f7e033da)

#### New
![ipamissueNew](https://github.com/liqotech/liqo/assets/33266330/a5da302e-7b97-480e-a08a-4189612608f2)

#### Network
```yaml
apiVersion: ipam.liqo.io/v1alpha1
kind: Network
metadata:
  name: res
  namespace: liqo-tenant
  labels:
    liqo.io/remote-cluster-id: "ABCDE"
spec:
  cidr: 10.10.0.0/16
status:
  cidr: 10.20.0.0/16
```
#### IP
```yaml
apiVersion: ipam.liqo.io/v1alpha1
kind: IP
metadata:
  name: res
  namespace: res
spec:
  ip: 1.2.3.4
  serviceTemplate:
    metadata:
      labels:
      annotations:
    spec:
      ports:
      - name: http
        targetPort: 80
        port: 80
      type: NodePort
status:
  ipMappings:
    ABCDE: 10.50.0.1
    ZYXWV: 10.60.0.3
```

## Why it is useful
Using a CRD that grants a higher level of abstraction gives some advantages:
- Liqo components don't need a gRPC client to acquire and remap an IP.
- Easy way to check and debug remapped IPs and CIDRs.
- Possibility to switch the core IPAM implementation maintaining a stable API.
