### ISSUE TITLE
Installation fail with conflict between the ports of the gateway and its load balancer

### ISSUE THREAD

**Issue by IceManGreen** [liqotech/liqo#2370]
#### What happened:

During the installation of Liqo, on the same node of a cluster, the Pod of the Gateway or the Pod of the LoadBalancer end with "Pending" status due to unavailable free ports on node.

More precisely, the pods of the LoadBalancer of the gateway are deploying as expected on all the other nodes.
Only the node where the pod of the gateway is deployed ends with a "Pending" status for the LoadBalancer or the Gateway pod (randomly). 

Example on a K3S cluster of 3 nodes :

```sh  
$ kubectl get pods -n liqo -o wide                                                                                           
NAME                                      READY   STATUS    RESTARTS   AGE   IP              NODE     NOMINATED NODE   READINESS GATES
# ...
kube-system     svclb-liqo-gateway-35183a08-6znjm               1/1     Running   0               4m39s   10.42.1.56      node1     <none>           <none>
kube-system     svclb-liqo-gateway-35183a08-7dxhs               1/1     Running   0               4m39s   10.42.2.80      node2   <none>           <none>
kube-system     svclb-liqo-gateway-35183a08-sntpj               1/1     Running   0               4m39s   10.42.0.39      node3     <none>           <none>
liqo            liqo-gateway-65bbfc94cf-rhzsp                   0/1     Pending   0               4m28s   <none>          <none>   <none>           <none>
```

When I describe the pod of the gateway I get this error event :

```sh
Events:
  Type     Reason            Age    From               Message
  ----     ------            ----   ----               -------
  Warning  FailedScheduling  3m57s  default-scheduler  0/3 nodes are available: 3 node(s) didn't have free ports for the requested pod ports. preemption: 0/3 nodes are available: 3 No preemption victims found for incoming pod..
  Warning  FailedScheduling  3m2s   default-scheduler  0/3 nodes are available: 3 node(s) didn't have free ports for the requested pod ports. preemption: 0/3 nodes are available: 3 No preemption victims found for incoming pod..
```

#### What you expected to happen:

I expect that everything is deployed as expected, with a status equals to "Running".

#### How to reproduce it (as minimally and precisely as possible):

- Install a K3S cluster with 3 nodes
- Install Liqo with `--set "gateway.service.type=LoadBalancer"`

The status of the Gateway pod or the status of the LoadBalancer pod on the same node will end with a "Pending" status.

#### Environment:

- Liqoctl version:
    - Client version: v0.9.4
    - Server version: v0.10.1 
    
- Kubernetes version (use `kubectl version`):
Client Version: v1.29.2
Server Version: v1.28.6+k3s2

- Cloud provider or hardware configuration:
Linux hypervisor, the K3S cluster is hosted on virtual machines deployed on QEMU/KVM with libvirt :

```
Compiled against library: libvirt 6.0.0
Using library: libvirt 6.0.0
Using API: QEMU 6.0.0
Running hypervisor: QEMU 4.2.1
```

- Node image:

```sh
$ uname -a
Linux controller 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux
```

**Comment by aleoli** [comment]
Hi @IceManGreen,

The issue is that both your lb and liqo gateway pods try to bind to the same port. If you change it in the values file, it is reflected on the pod and service.

You have two possible solutions:
* use node port services
* run the installation with the flag `--set "gateway.service.type=LoadBalancer,gateway.config.listeningPort=5873"` and then edit your service to listen the port 5871

We will fix this in the next release by avoiding the usage of host ports and host networks.

**Comment by IceManGreen** [comment]
Thank you, it works indeed !

For anyone looking for a temporary solution for the LoadBalancer, what I did exactly is :

```sh
liqoctl install k3s --cluster-name domain-1 \
    --api-server-url <url> \
    --set "gateway.service.type=LoadBalancer,gateway.config.listeningPort=5873" \
```

(Like @aleoli said)

Then edit the LoadBalancer Daemonset with `kubectl edit daemonset/svclb-liqo-gateway-2fe6dd49 -n kube-system` (or according to the name of your daemonset) with :

 ```yaml
 # ...
 spec:
  template:
    spec:
      containers:
      - env:
        - name: SRC_PORT
         # HERE >
          value: "5871"
        - name: SRC_RANGES
          value: 0.0.0.0/0
        - name: DEST_PROTO
          value: UDP
        - name: DEST_PORT
          value: "5873"
        - name: DEST_IPS
          value: 10.43.232.220
        image: rancher/klipper-lb:v0.4.5
        imagePullPolicy: IfNotPresent
        # HERE (to avoid confusions) >
        name: lb-udp-5871
        ports:
       # HERE (all the ports) >
        - containerPort: 5871
          hostPort: 5871
          name: lb-udp-5871
          protocol: UDP
```

Apply the modifications and watch the installation end with success :)
