### ISSUE TITLE
Liqo install using --enable-metric flag

### ISSUE THREAD

**Issue by thisiskazem** [liqotech/liqo#2805]
#### What happened:
I saw no difference with or without defining the flag using this command:
sudo liqoctl install k3s --kubeconfig=/etc/rancher/k3s/k3s.yaml --enable-metrics
#### What you expected to happen:
I expected for the creation of a servicemonitor for liqo so the prometheus could be able to use it to collect metric
#### How to reproduce it (as minimally and precisely as possible):
I could only do it using the helm installation and by modifying the values.yaml file
#### Environment:
- Liqo version: v1.0.0-rc2
- Liqoctl version: v1.0.0-rc2
- Kubernetes version (use `kubectl version`): k3s
- Cloud provider or hardware configuration:
- Node image:
- Network plugin and version:
- Install tools:
- Others:

**Comment by cheina97** [comment]
Hi @thisiskazem, are you sure your prometheus operator has been configured properly? By default, it cannot scrape metrics outside of the namespace it has been installed.

**Comment by cheina97** [comment]
I suggest to install prometheus with this values (i used the (kube-prometheus-stack)[https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack])
```
prometheus:
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
```
