### ISSUE TITLE
ResourceSlice not generating virutalnode

### ISSUE THREAD

**Issue by jv4n5e** [liqotech/liqo#3046]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

1.0.0

### What happened?

I came up with the following script to automate declarative peering:

```
#!/usr/bin/env bash
set -exuo pipefail
IFS=$'\n\t'

#---------------------------------------
# Usage & Argument Validation
#---------------------------------------
usage() {
  cat <<EOF
Usage: $0 <provider_cluster> <consumer_cluster>
  provider_cluster  Name of the provider EKS cluster (name should match a directory in here).
  consumer_cluster  Name of the consumer EKS cluster (name should match a directory in here).
EOF
  exit 1
}

[[ $# -eq 2 ]] || usage
provider_cluster=$1
consumer_cluster=$2

#---------------------------------------
# Extract region from cluster name suffix
#   – if it ends with e.g. “us-west-2” use that
#   – otherwise default to us-east-1
#---------------------------------------
extract_region() {
  local name=$1
  if [[ $name =~ ([a-z]{2}-[a-z]+-[0-9]+)$ ]]; then
    echo "${BASH_REMATCH[1]}"
  else
    echo "us-east-1"
  fi
}

provider_region=$(extract_region "$provider_cluster")
consumer_region=$(extract_region "$consumer_cluster")

provider_context=arn:aws:eks:${provider_region}:${AWS_ACCOUNT_ID_DEV}:cluster/${provider_cluster}
consumer_context=arn:aws:eks:${consumer_region}:${AWS_ACCOUNT_ID_DEV}:cluster/${consumer_cluster}

#---------------------------------------
# Environment Variables
#---------------------------------------
export env=dev

#---------------------------------------
# Main Execution
#---------------------------------------

echo "Updating kubeconfig for consumer cluster"
aws eks update-kubeconfig \
  --region "${consumer_region}" \
  --name "${consumer_cluster}" \
  --alias "${consumer_cluster}" \
  --role-arn "${aws_role_arn}"

consumer_cluster_id=$(kubectl get configmaps -n $sg_cust_cluster_namespace liqo-clusterid-configmap --template {{.data.CLUSTER_ID}})

kubectl create ns $peer_ns_consumer --dry-run=client -o yaml | kubectl apply -f -
kubectl label ns $peer_ns_consumer liqo.io/tenant-namespace='true'
consumer_cluster_liqo_cidr=$(kubectl get networks.ipam.liqo.io -n $sg_cust_cluster_namespace external-cidr -o=jsonpath={'.status.cidr'})
consumer_cluster_pod_cidr=$(kubectl get networks.ipam.liqo.io -n $sg_cust_cluster_namespace pod-cidr -o=jsonpath={'.status.cidr'})

echo "Updating kubeconfig for provider cluster"
aws eks update-kubeconfig \
  --region "${provider_region}" \
  --name "${provider_cluster}" \
  --alias "${provider_cluster}" \
  --role-arn "${aws_role_arn}"

provider_cluster_id=$(kubectl get configmaps -n $sg_cust_cluster_namespace liqo-clusterid-configmap --template {{.data.CLUSTER_ID}})
provider_cluster_liqo_cidr=$(kubectl get networks.ipam.liqo.io -n $sg_cust_cluster_namespace external-cidr -o=jsonpath={'.status.cidr'})
provider_cluster_pod_cidr=$(kubectl get networks.ipam.liqo.io -n $sg_cust_cluster_namespace pod-cidr -o=jsonpath={'.status.cidr'})
kubectl create ns $peer_ns_provider --dry-run=client -o yaml | kubectl apply -f -
kubectl label ns $peer_ns_provider liqo.io/tenant-namespace='true'
kubectl label ns $peer_ns_provider liqo.io/remote-cluster-id=$consumer_cluster_id
kubectl apply -n $peer_ns_provider -f - <<EOF
apiVersion: networking.liqo.io/v1beta1
kind: Configuration
metadata:
  labels:
    liqo.io/remote-cluster-id: $consumer_cluster_id
  name: $peer_ns_provider
spec:
  remote:
    cidr:
      external: ["$consumer_cluster_liqo_cidr"]
      pod: ["$consumer_cluster_pod_cidr"]
EOF

kubectl config use-context $consumer_cluster
kubectl label ns $peer_ns_consumer liqo.io/remote-cluster-id=$provider_cluster_id
kubectl apply -n $peer_ns_consumer -f - <<EOF
apiVersion: networking.liqo.io/v1beta1
kind: Configuration
metadata:
  labels:
    liqo.io/remote-cluster-id: $provider_cluster_id
  name: $peer_ns_consumer
spec:
  remote:
    cidr:
      external: ["$provider_cluster_liqo_cidr"]
      pod: ["$provider_cluster_pod_cidr"]
EOF

openssl genpkey -algorithm X25519 -outform der -out private_consumer.der
openssl pkey -inform der -in private_consumer.der -pubout -outform der -out public_consumer.der
wg_private_key_consumer=$(cat private_consumer.der | tail -c 32 | base64)
wg_public_key_consumer=$(cat public_consumer.der | tail -c 32 | base64)
openssl genpkey -algorithm X25519 -outform der -out private_provider.der
openssl pkey -inform der -in private_provider.der -pubout -outform der -out public_provider.der
wg_private_key_provider=$(cat private_provider.der | tail -c 32 | base64)
wg_public_key_provider=$(cat public_provider.der | tail -c 32 | base64)

kubectl apply -n $peer_ns_consumer -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  labels:
    liqo.io/remote-cluster-id: $provider_cluster_id
  name: gw-keys
type: Opaque
data:
  privateKey: $wg_private_key_consumer
  publicKey: $wg_public_key_consumer
EOF

kubectl apply -n $peer_ns_consumer -f - <<EOF
apiVersion: networking.liqo.io/v1beta1
kind: GatewayClient
metadata:
  creationTimestamp: null
  labels:
    liqo.io/remote-cluster-id: $provider_cluster_id
  name: client
spec:
  clientTemplateRef:
    apiVersion: networking.liqo.io/v1beta1
    kind: WgGatewayClientTemplate
    name: wireguard-client
    namespace: $sg_cust_cluster_namespace
  secretRef:
    name: gw-keys
  endpoint:
    addresses:
    - <REMOTE_IP>
    port: 30742
    protocol: UDP
  mtu: 1340
EOF

kubectl apply -n $peer_ns_consumer -f - <<EOF
apiVersion: networking.liqo.io/v1beta1
kind: PublicKey
metadata:
  labels:
    liqo.io/remote-cluster-id: $provider_cluster_id
    networking.liqo.io/gateway-resource: "true"
  name: gw-publickey
spec:
  publicKey: $wg_public_key_provider
EOF

kubectl config use-context $provider_cluster

kubectl apply -n $peer_ns_provider -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  labels:
    liqo.io/remote-cluster-id: $consumer_cluster_id
  name: gw-keys
type: Opaque
data:
  privateKey: $wg_private_key_provider
  publicKey: $wg_public_key_provider
EOF

kubectl apply -n $peer_ns_provider -f - <<EOF
apiVersion: networking.liqo.io/v1beta1
kind: GatewayServer
metadata:
  labels:
    liqo.io/remote-cluster-id: $consumer_cluster_id
  name: server
spec:
  endpoint:
    port: 51840
    serviceType: LoadBalancer
  mtu: 1340
  secretRef:
    name: gw-keys
  serverTemplateRef:
    apiVersion: networking.liqo.io/v1beta1
    kind: WgGatewayServerTemplate
    name: wireguard-server
    namespace: $sg_cust_cluster_namespace
EOF

kubectl apply -n $peer_ns_provider -f - <<EOF
apiVersion: networking.liqo.io/v1beta1
kind: PublicKey
metadata:
  labels:
    liqo.io/remote-cluster-id: $consumer_cluster_id
    networking.liqo.io/gateway-resource: "true"
  name: gw-publickey
spec:
  publicKey: $wg_public_key_consumer
EOF

kubectl apply -n $peer_ns_provider -f - <<EOF
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    liqo.io/remote-cluster-id: $consumer_cluster_id
  name: liqo-binding-liqo-remote-controlplane
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: liqo-remote-controlplane
subjects:
  - kind: User
    name: $iam_user
    apiGroup: rbac.authorization.k8s.io
EOF

kubectl apply -n $peer_ns_provider -f - <<EOF
apiVersion: authentication.liqo.io/v1beta1
kind: Tenant
metadata:
  labels:
    liqo.io/remote-cluster-id: $consumer_cluster_id
  name: $peer_ns_provider
spec:
  clusterID: $consumer_cluster_id
  authzPolicy: TolerateNoHandshake
  tenantCondition: Active
EOF

TOKEN=$(aws eks get-token \
  --cluster-name $provider_cluster \
  --query 'status.token' --output text)

kubectl config set-credentials $iam_user --token="$TOKEN"

kubectl config set-context $iam_user \
  --cluster=$provider_context \
  --user=$iam_user

kubectl config use-context $iam_user

kubectl auth can-i get resourceslice -n $peer_ns_consumer

kubecfg=$(kubectl config view --raw --minify | base64 | tr -d '\r\n')

kubectl config use-context $consumer_cluster

kubectl apply -n $peer_ns_consumer -f - <<EOF
apiVersion: v1
data:
  kubeconfig: ${kubecfg}
kind: Secret
metadata:
  labels:
    liqo.io/identity-type: ControlPlane
    liqo.io/remote-cluster-id: $provider_cluster_id
  annotations:
    liqo.io/remote-tenant-namespace: $peer_ns_consumer
  name: cplane-secret
EOF

kubectl apply -n $peer_ns_consumer -f - <<EOF
apiVersion: authentication.liqo.io/v1beta1
kind: ResourceSlice
metadata:
  annotations:
    liqo.io/create-virtual-node: "true"
  creationTimestamp: null
  labels:
    liqo.io/remote-cluster-id: $provider_cluster_id
    liqo.io/remoteID: $provider_cluster_id
  name: test
spec:
  class: default
  providerClusterID: $provider_cluster_id
  resources:
    cpu: 16
    memory: 56Gi
EOF
```
The CRD replicator pod logs display the output that the docs exemplify, but the virtual node is not created, and the ResourceSlice CR status is not updated. What am I missing?

Also, unrelated: if you could provide a better way to embed into the kubeconfig for the consumer cluster an EKS token that does not expire, it would be great, since after 15 minutes of the script being executed the secret stops working.

### Relevant log output

```shell

```

### How can we reproduce the issue?

1. Run the provided script, making sure to provide the params in the script execution, the AWS_ACCOUNT_ID_DEV env var, and that the IAM user being used has access to both EKS clusters.

### Provider or distribution

EKS

### Kubernetes Version

1.31

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by claudiolor** [comment]
Hi @jv4n5e, when you create a ResourceSlice, on the provider cluster new credentials are automatically generated to allow the consumer cluster to offload workloads and replicate resources on the provider. However, this is handled differently in EKS, where Liqo needs to directly interact with the IAM. 
So, do understand what is going on:
- How did you install Liqo? Did you specify EKS as provider? (to enable the user creation via IAM)
- Can you please check whether ther ResourceSlice has been replicated **on the provider cluster** and its status updated?
   ```
   kubectl get resourceslice -A
   ```
- Can you please share the logs of the `liqo-controller-manager` **on the provider cluster**?

**Comment by jv4n5e** [comment]
Hi @claudiolor .
One of the main reasons I went with declarative peering is to avoid using 'liqoctl peer' which creates liqo users on IAM per cluster; we would like the peering to use a specific IAM user with all required permissions for both EKS clusters. Is that possible through liqoctl command?
I installed Liqo through helm charts. Here are the values I am using:
```
apiServer:
    ca: ""
    trustedCA: false
authentication:
    awsConfig:
        useExistingSecret: true
        accessKeyId:
            secretKeyRef:
                name: mysecret
                key: AWS_ACCESS_KEY_ID
        secretAccessKey:
            secretKeyRef:
                name: mysecret
                key: AWS_SECRET_ACCESS_KEY
    enabled: true
common:
    affinity: {}
    extraArgs: []
    globalAnnotations: {}
    globalLabels:
        liqo.io/managed: "true"
    nodeSelector: {}
    tolerations: []
controllerManager:
    config:
        defaultLimitsEnforcement: None
        enableNodeFailureController: false
        enableResourceEnforcement: true
    image:
        name: ghcr.io/liqotech/liqo-controller-manager
        version: ""
    metrics:
        service:
            annotations: {}
            labels: {}
        serviceMonitor:
            enabled: false
            interval: ""
            labels: {}
            scrapeTimeout: ""
    pod:
        annotations: {}
        extraArgs: []
        labels:
            company/control-plane: "true"
            company/provider: company
        priorityClassName: ""
        resources:
            limits: {}
            requests: {}
    replicas: 1
crdReplicator:
    image:
        name: ghcr.io/liqotech/crd-replicator
        version: ""
    metrics:
        podMonitor:
            enabled: false
            interval: ""
            labels: {}
            scrapeTimeout: ""
    pod:
        annotations: {}
        extraArgs: []
        labels:
            company/control-plane: "true"
            company/provider: company
        priorityClassName: ""
        resources:
            limits: {}
            requests: {}
discovery:
    config:
        clusterLabels:
            liqo.io/provider: eks
fullnameOverride: ""
ipam:
    external:
        enabled: false
        url: ""
    externalCIDR: 10.70.0.0/16
    internal:
        graphviz: false
        image:
            name: ghcr.io/liqotech/ipam
            version: ""
        pod:
            annotations: {}
            extraArgs: []
            labels: {}
            priorityClassName: ""
            resources:
                limits: {}
                requests: {}
        replicas: 1
        syncGracePeriod: 30s
        syncInterval: 2m
    internalCIDR: 10.80.0.0/16
    pools:
        - 10.0.0.0/8
        - 192.168.0.0/16
        - 172.16.0.0/12
    reservedSubnets: []
    serviceCIDR: 172.20.0.0/16
metricAgent:
    config:
        timeout:
            read: 30s
            write: 30s
    enabled: true
    image:
        name: ghcr.io/liqotech/metric-agent
        version: ""
    initContainer:
        image:
            name: ghcr.io/liqotech/cert-creator
            version: ""
    pod:
        annotations: {}
        extraArgs: []
        labels: {}
        priorityClassName: ""
        resources:
            limits: {}
            requests: {}
metrics:
    enabled: true
    prometheusOperator:
        enabled: false
nameOverride: ""
networking:
    clientResources:
        - apiVersion: networking.liqo.io/v1beta1
          resource: wggatewayclients
    enabled: true
    fabric:
        config:
            fullMasquerade: true
            gatewayMasqueradeBypass: false
            healthProbeBindAddressPort: "8081"
            metricsAddressPort: "8082"
            nftablesMonitor: false
        image:
            name: ghcr.io/liqotech/fabric
            version: ""
        pod:
            annotations: {}
            extraArgs: []
            labels:
                company/cluster-id: e6a207d9-0156-4d2c-8310-a333c91d7409
                company/control-plane: "true"
                company/provider: company
            priorityClassName: ""
            resources:
                limits: {}
                requests: {}
        tolerations: []
    gatewayTemplates:
        container:
            gateway:
                image:
                    name: ghcr.io/liqotech/gateway
                    version: ""
            geneve:
                image:
                    name: ghcr.io/liqotech/gateway/geneve
                    version: ""
            wireguard:
                image:
                    name: ghcr.io/liqotech/gateway/wireguard
                    version: ""
        ping:
            interval: 2s
            lossThreshold: 5
            updateStatusInterval: 10s
        replicas: 1
        server:
            service:
                allocateLoadBalancerNodePorts: ""
                annotations:
                    service.beta.kubernetes.io/aws-load-balancer-type: nlb
        wireguard:
            implementation: kernel
    genevePort: 6091
    reflectIPs: true
    serverResources:
        - apiVersion: networking.liqo.io/v1beta1
          resource: wggatewayservers
offloading:
    createNode: true
    defaultNodeResources:
        cpu: "4"
        ephemeral-storage: 20Gi
        memory: 8Gi
        pods: "110"
    disableNetworkCheck: false
    enabled: true
    reflection:
        configmap:
            type: AllowList
            workers: 3
        endpointslice:
            workers: 10
        event:
            type: AllowList
            workers: 3
        ingress:
            ingressClasses: []
            type: AllowList
            workers: 0
        persistentvolumeclaim:
            workers: 0
        pod:
            workers: 10
        secret:
            type: AllowList
            workers: 0
        service:
            loadBalancerClasses: []
            type: DenyList
            workers: 3
        serviceaccount:
            workers: 0
        skip:
            annotations:
                - cloud.google.com/neg
                - cloud.google.com/neg-status
                - kubernetes.digitalocean.com/load-balancer-id
                - ingress.kubernetes.io/backends
                - ingress.kubernetes.io/forwarding-rule
                - ingress.kubernetes.io/target-proxy
                - ingress.kubernetes.io/url-map
                - metallb.universe.tf/address-pool
                - metallb.universe.tf/ip-allocated-from-pool
                - metallb.universe.tf/loadBalancerIPs
                - loadbalancer.openstack.org/load-balancer-id
            labels: []
    runtimeClass:
        annotations: {}
        handler: liqo
        labels: {}
        name: liqo
        nodeSelector:
            enabled: true
            labels:
                liqo.io/type: virtual-node
        tolerations:
            enabled: true
            tolerations:
                - effect: NoExecute
                  key: virtual-node.liqo.io/not-allowed
                  operator: Exists
openshiftConfig:
    enabled: false
    virtualKubeletSCCs:
        - anyuid
        - privileged
proxy:
    config:
        listeningPort: 8118
    enabled: true
    image:
        name: ghcr.io/liqotech/proxy
        version: ""
    pod:
        annotations: {}
        extraArgs: []
        labels: {}
        priorityClassName: ""
        resources:
            limits: {}
            requests: {}
    replicas: 1
    service:
        annotations: {}
        type: ClusterIP
pullPolicy: IfNotPresent
requirements:
    kernel:
        disabled: false
        enabled: true
storage:
    enabled: true
    realStorageClassName: ""
    storageNamespace: liqo-storage
    virtualStorageClassName: liqo
tag: v1.0.0
telemetry:
    config:
        schedule: ""
    enabled: false # this disables a cronjob that sends data to Liqo devs.
    image:
        name: ghcr.io/liqotech/telemetry
        version: ""
    pod:
        annotations: {}
        extraArgs: []
        labels: {}
        resources:
            limits: {}
            requests: {}
uninstaller:
    image:
        name: ghcr.io/liqotech/uninstaller
        version: ""
    pod:
        annotations: {}
        extraArgs: []
        labels: {}
        resources:
            limits: {}
            requests: {}
virtualKubelet:
    extra:
        annotations: {}
        args: []
        labels:
            company/control-plane: "true"
            company/provider: company
        resources:
            limits: {}
            requests: {}
    image:
        name: ghcr.io/liqotech/virtual-kubelet
        version: ""
    metrics:
        enabled: false
        podMonitor:
            enabled: false
            interval: ""
            labels: {}
            scrapeTimeout: ""
        port: 5872
    replicas: 1
    virtualNode:
        extra:
            annotations: {}
            labels: {}
webhook:
    failurePolicy: Fail
    image:
        name: ghcr.io/liqotech/webhook
        version: ""
    metrics:
        service:
            annotations: {}
            labels: {}
        serviceMonitor:
            enabled: false
            interval: ""
            labels: {}
            scrapeTimeout: ""
    patch:
        image: k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.1.1
    pod:
        annotations: {}
        extraArgs: []
        labels:
            company/control-plane: "true"
            company/provider: company
        priorityClassName: ""
        resources:
            limits: {}
            requests: {}
    port: 9443
    replicas: 1
```
I also expect the resourceslice to be replicated in the provider cluster, but it's missing.
Below are the controller manager logs:
```
E0521 23:22:18.986862       1 server_controller.go:92] Unable to ensure the internal fabric for the gateway server "sg-peer-us-west-2/server": internal endpoint not found for the gateway server "server"
E0521 23:22:18.986921       1 controller.go:316] "Reconciler error" err="internal endpoint not found for the gateway server \"server\"" controller="gatewayserver_internal" controllerGroup="networking.liqo.io" controllerKind="GatewayServer" GatewayServer="sg-peer-us-west-2/server" namespace="sg-peer-us-west-2" name="server" reconcileID="d8a8f720-0e5d-419a-b0fe-efb51b2d75e8"
E0521 23:22:19.380905       1 signal_unix.go:925] "Observed a panic" controller="wggatewayserver" controllerGroup="networking.liqo.io" controllerKind="WgGatewayServer" WgGatewayServer="sg-peer-us-west-2/server" namespace="sg-peer-us-west-2" name="server" reconcileID="5c613550-3de3-4384-9506-177991486b1b" panic="runtime error: invalid memory address or nil pointer dereference" panicGoValue="\"invalid memory address or nil pointer dereference\"" stacktrace=<
    goroutine 1441 [running]:
    k8s.io/apimachinery/pkg/util/runtime.logPanic({0x2399ce0, 0x40084eec90}, {0x1b5d820, 0x37d2390})
        /go/pkg/mod/k8s.io/apimachinery@v0.31.2/pkg/util/runtime/runtime.go:107 +0x98
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile.func1()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.2/pkg/internal/controller/controller.go:105 +0xf0
    panic({0x1b5d820?, 0x37d2390?})
        /usr/local/go/src/runtime/panic.go:792 +0x124
    github.com/liqotech/liqo/pkg/liqo-controller-manager/networking/external-network/wireguard.(*WgGatewayServerReconciler).Reconcile(0x40009ed500, {0x2399ce0, 0x40084eec90}, {{{0x40143da468, 0x11}, {0x400ab7a206, 0x6}}})
        /tmp/builder/pkg/liqo-controller-manager/networking/external-network/wireguard/wggatewayserver_controller.go:190 +0x5f4
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile(0x400fc6eb40?, {0x2399ce0?, 0x40084eec90?}, {{{0x40143da468?, 0x0?}, {0x400ab7a206?, 0x0?}}})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.2/pkg/internal/controller/controller.go:116 +0x9c
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler(0x23b6f00, {0x2399d18, 0x4000910aa0}, {{{0x40143da468, 0x11}, {0x400ab7a206, 0x6}}})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.2/pkg/internal/controller/controller.go:303 +0x2ac
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem(0x23b6f00, {0x2399d18, 0x4000910aa0})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.2/pkg/internal/controller/controller.go:263 +0x184
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.2/pkg/internal/controller/controller.go:224 +0x80
    created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2 in goroutine 271
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.2/pkg/internal/controller/controller.go:220 +0x3c4
 >
```
Thank you!
